# copied defaults options

# only real thing that matters is which providers I'm using
# I listed some default providers to use
# ones not listed are not being used by me
[providers]
default = [
  "desktopapplications",
  "bluetooth",
  "files",
  "calc",
  "runner",
  "websearch",
  "providerlist",
  "menus",
]
#
# empty = ["desktopapplications"] # providers to be queried when query is empty
# ignore_preview = [] # providers that should not show previews
max_results = 20 # global max results

# [[providers.prefixes]]
# prefix = ";"
# provider = "providerlist"
#
# [[providers.prefixes]]
# prefix = ">"
# provider = "runner"
#
# [[providers.prefixes]]
# prefix = "/"
# provider = "files"
#
# [[providers.prefixes]]
# prefix = "="
# provider = "calc"
#
# [[providers.prefixes]]
# prefix = "@"
# provider = "websearch"


# actual stuff different from defaults that I'm adding
[[providers.prefixes]]
prefix = "\\"
provider = "menus:power"

[[providers.prefixes]]
prefix = "/s"
provider = "menus:steam"
